// Filter Mutations
export const UPDATE_NR_FILTER = "UPDATE_NR_FILTER"
export const UPDATE_DO_FILTER = "UPDATE_DO_FILTER"
export const ADD_NARRATIVE_RELATIONSHIP_TO_FILTER = "ADD_NARRATIVE_RELATIONSHIP_TO_FILTER"
export const ADD_DATA_OPERATION_TO_FILTER = "ADD_DATA_OPERATION_TO_FILTER"

// Design Space Mutations
export const SET_NARRATIVE_RELATIONSHIP = "SET_NARRATIVE_RELATIONSHIP"
export const SET_DATA_OPERATION = "SET_DATA_OPERATION"
export const SET_TRANSITION_CARDS = "SET_TRANSITION_CARDS"
export const SET_EDITORIAL_LAYERS = "SET_EDITORIAL_LAYERS"
export const SET_TRANSITION_EFFECTS = "SET_TRANSITION_EFFECTS"

// Page Management Mutations
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE"
